#!/usr/bin/env python3
from pagebuilder import PageBuilder

builder = PageBuilder("./pages", "./templates", "./assets", "./.dist")

if __name__ == "__main__":
    from pagebuilder import cli

    cli([builder])
